language: java
sudo: true
jdk:
  - openjdk15

script:
  - ./mvnw clean install -B
jobs:
  include:
    - stage: test
      script: ./mvnw clean test
before_install:
  - chmod +x mvnw

#deploy:
#  provider: heroku
#  api_key: $HEROKU_API_KEY
#  app: clientconnectivity



